# Exploration of TileDB with sample data

## Setup

In [4]:
import tiledb

In [7]:
tiledb.__version__

'0.6.6'

## Retrieve sample data

In [33]:
# Get sample CSV
import urllib.request
urllib.request.urlretrieve('https://covid.ourworldindata.org/data/owid-covid-data.csv', 'owid-covid-data.csv')

('owid-covid-data.csv', <http.client.HTTPMessage at 0x1194fb5d0>)

In [44]:
# Confirm that this is a valid CSV
import pandas
pandas.read_csv('owid-covid-data.csv')

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,ABW,North America,Aruba,2020-03-13,2.0,2.0,NaN,NaN,0.0,NaN,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
1,ABW,North America,Aruba,2020-03-19,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
2,ABW,North America,Aruba,2020-03-20,4.0,2.0,0.286,NaN,0.0,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
3,ABW,North America,Aruba,2020-03-21,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
4,ABW,North America,Aruba,2020-03-22,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52005,NaN,NaN,International,2020-10-19,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52006,NaN,NaN,International,2020-10-20,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52007,NaN,NaN,International,2020-10-21,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52008,NaN,NaN,International,2020-10-22,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52009,NaN,NaN,International,2020-10-23,696.0,NaN,NaN,7.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Load data

In [47]:
# If already exists, delete first.
import shutil
shutil.rmtree('owid-covid-data.tldb', ignore_errors=True)

tiledb.from_csv('owid-covid-data.tldb', 'owid-covid-data.csv')

TypeError: Failed to convert buffer for attribute: 'iso_code'